# Generated by Django 4.1.2 on 2022-11-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
